### ISSUE TITLE
请问这里判断是否在一个子网里为什么是看mask 而不是 IP&mask 呢

### ISSUE THREAD

**Issue by Cobalt-27** [KOISHI-CHEN/CS305-2022-PA3-QA#5]
![Screenshot 2022-05-12 100006](https://user-images.githubusercontent.com/34511059/167977009-d4df7d0a-8f46-4446-b4e9-19968dec2c5f.jpg)

**Comment by KOISHI-CHEN** [comment]
应该是笔误。的确是看IP&mask
